/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./../components/AppHeader.vue')['default']
    AudioDock: typeof import('./../components/AudioDock.vue')['default']
    CaseCover: typeof import('./../components/CaseCover.vue')['default']
    ClueCard: typeof import('./../components/ClueCard.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    EvidenceBoard: typeof import('./../components/EvidenceBoard.vue')['default']
    InvestigationTerminal: typeof import('./../components/InvestigationTerminal.vue')['default']
    MaterialTag: typeof import('./../components/MaterialTag.vue')['default']
    PuzzlePanel: typeof import('./../components/PuzzlePanel.vue')['default']
    ReasoningPanel: typeof import('./../components/ReasoningPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareCardDialog: typeof import('./../components/ShareCardDialog.vue')['default']
    SubmitCaseDialog: typeof import('./../components/SubmitCaseDialog.vue')['default']
    TimelinePanel: typeof import('./../components/TimelinePanel.vue')['default']
  }
}
